service_man/urls.py
from django.urls import path
from django.contrib.auth import views

from service_man import views as v

app_name='service_man'

urlpatterns = [

    path('',v.IndexView.as_view(),name='index'),
    path('pending_request',v.PendingRequestView.as_view(),name='pending_request'),
    path('past_request',v.PastRequestView.as_view(),name='past_request'),
    path('service_done_request',v.ServiceDoneRequestView.as_view(),name='service_done_request'),
    path('request_detail/<int:pk>/',v.RequestDetailView.as_view(),name='request_detail'),
    path('request_update/<int:pk>',v.ServicesRequestUpdateView.as_view(),name='request_update'),

    path('login',views.LoginView.as_view(template_name='service_man/login.html'),name='login'),
    path('logout',views.LogoutView.as_view(),name='logout'),

]

smartservicebuddy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('client_request.urls')),
    path('service_man/',include('service_man.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_title = "SmartServiceBuddy"
admin.site.site_header = "SmartServiceBuddy Admin Login"

service_man/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

appliance_type_CHOICES = (
    ('refrigerator','Refrigerator'),
    ('microwave oven', 'Microwave oven'),
    ('washing machine', 'Washing machine'),
    ('dishwasher', 'Dishwasher'),
    ('air conditioner', 'Air conditioner'),
    ('water heater', 'Water heater'),
    ('air purifier', 'Air purifier'),
    ('ceiling fan', 'Ceiling fan'),
    ('vacuum Cleaner', 'Vacuum Cleaner'),
    ('hair dryer', 'Hair dryer'),
    ('water purifier', 'Water purifier'),
    ('other', 'Other'),
)


class ServiceManInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pic',blank=True)
    #type_appliance_service=models.CharField(max_length=50,choices=sorted(appliance_type_CHOICES))
    #pincode_service=models.PositiveIntegerField()

    def __str__(self):
        return  self.user.username

service_man/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.generic import (TemplateView,ListView,
                                    DetailView,CreateView,UpdateView,DeleteView )
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from service_man.models import ServiceManInfo
from client_request.models import ClientRequest
from client_request.forms import ClientRequestForm, UpdateClientRequestForm



# Create your views here.

class IndexView(TemplateView):
    template_name = 'service_man/index.html'


class PendingRequestView(ListView,LoginRequiredMixin):
    model = ClientRequest
    template_name = 'service_man/pending_request.html'
    def get_queryset(self):
       return ClientRequest.objects.filter(appointment_date__gte=timezone.now(),request_status='service_pending').order_by('appointment_date')

class PastRequestView(ListView,LoginRequiredMixin):
    model = ClientRequest
    template_name = 'service_man/past_request.html'
    def get_queryset(self):
       return ClientRequest.objects.filter(appointment_date__lt=timezone.now() ,request_status='service_done').order_by('-appointment_date')

class ServiceDoneRequestView(ListView,LoginRequiredMixin):
    model = ClientRequest
    template_name = 'service_man/service_done_request.html'
    def get_queryset(self):
       return ClientRequest.objects.filter(request_status='service_done').order_by('-appointment_date')




class RequestDetailView(DetailView,LoginRequiredMixin):
    model = ClientRequest
    template_name = 'service_man/request_detail.html'
"""
def ServicesRequestUpdateView(request,pk):
    form = UpdateClientRequestForm()
    user = ClientRequest.objects.get(pk=pk)
    if request.method == "POST":
        form = UpdateClientRequestForm(request.POST)
        if form.is_valid():

            request_detail = form.save(commit=True)
            #charge = form.cleaned_data['charge']
            #user.charge = charge
            request_detail.save()
    return render(request,'service_man/update_request_form.html')
"""
class ServicesRequestUpdateView(UpdateView,LoginRequiredMixin,):
    model = ClientRequest
    template_name = 'service_man/update_request_form.html'
    form_class = UpdateClientRequestForm
    login_url = 'service_man/login'
    #redirect_field_name = 'request_detail'
    success_url = reverse_lazy('service_man:pending_request')

service_man/templates/service_man/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
{% block title %}{% endblock %}</title>

    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {# Fonts#}
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">


	<style>
body{
  background-image: url("{% static 'images/05.jpg' %}");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size:  cover;
}
.navbar{
height:auto;
font-size:16px;
}

.inputBox input
{
	width:100%;
	padding:10px 0;
	font-size:16px;
	color:#fff;
	letter-spacing:1.1px;
	margin-bottom:30px;
	border:none;
	border-bottom:1px solid #fff;
	outline:none;
	background:transparent;
}
.inputBox label
{
	position:absolute;
	top:0;
	left:0;
	padding:10px 0;
	font-size:16px;
	color:#fff;
	pointer-events:none;
	transition: .5s;
}


@media only screen and (min-width: 600px) {
  /* For tablets: */
  .col-s-1 {width: 8.33%;}
  .col-s-2 {width: 16.66%;}
  .col-s-3 {width: 25%;}
  .col-s-4 {width: 33.33%;}
  .col-s-5 {width: 41.66%;}
  .col-s-6 {width: 50%;}
  .col-s-7 {width: 58.33%;}
  .col-s-8 {width: 66.66%;}
  .col-s-9 {width: 75%;}
  .col-s-10 {width: 83.33%;}
  .col-s-11 {width: 91.66%;}
  .col-s-12 {width: 100%;}
}
@media only screen and (min-width: 768px) {
  /* For desktop: */
  .col-1 {width: 8.33%;}
  .col-2 {width: 16.66%;}
  .col-3 {width: 25%;}
  .col-4 {width: 33.33%;}
  .col-5 {width: 41.66%;}
  .col-6 {width: 50%;}
  .col-7 {width: 58.33%;}
  .col-8 {width: 66.66%;}
  .col-9 {width: 75%;}
  .col-10 {width: 83.33%;}
  .col-11 {width: 91.66%;}
  .col-12 {width: 100%;}
}


</style>

</head>


  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">


            <a class="navbar-brand" href="{% url 'service_man:index' %}">HOME</a>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
           {% if user.is_authenticated%}
            <a class="nav-item nav-link font-italic font-weight-bold" href="{% url 'service_man:pending_request' %}">Pending Request</a>
            <a class="nav-item nav-link font-italic font-weight-bold" href="{% url 'service_man:past_request' %}">Past Request </a>
           <a class="nav-item nav-link font-italic font-weight-bold" href="{% url 'service_man:service_done_request' %}">Service Done Request </a>


            <a class="nav-item nav-link font-italic font-weight-bold" href="{% url 'admin:logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link font-italic font-weight-bold" href="{% url 'service_man:login' %}">LogIn</a>
            {% endif %}
        </div>
  </div>

    </nav>

<div >
{%  block content %}
{% endblock %}
</div>

<!-- Footer -->

<footer class="page-footer font-small blue pt-4">
<img class="img-responsive" src="{% static 'images/boarder.jpg' %}" alt="" width="100%" height="5px">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">

      <!-- Grid row -->
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 class="text-uppercase">Smart Service Buddy</h5>
          <p>Perfect destination for your favourite appliances.</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Contact US:</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!">	Corporate Office: 7th floor, Apollo Premier,Vijay Nagar,Indore- 400092.
</a>

              </li>
                <br>
              <li>
                <a href="#!">Toll Free No: 7415550155</a>
              </li>
              <li>
                <a href="#!">Business Hours: 10am - 7pm</a>
              </li>
              <li>
                <a href="#!">E mails: enquiries@smartservicebuddy.in</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Navigation</h5>

            <ul class="list-unstyled">
              <li>
                <a href="{% url 'index' %}">Home</a>
              </li>
              <li>
                <a href="{% url 'service_request' %}">Service Request</a>
              </li>
              <li>
                <a href="{% url 'admin:login' %}">Admin</a>
              </li>
              <li>
                <a href="{% url 'service_man:login' %}">ServiceMan</a>
              </li>
                 <li>
                <a href="{% url 'search' %}">Track  Request</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href=""> SmartServiceBuddy</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

  </body>
</html>

service_man/templates/service_man/index.html
{% extends 'service_man/base.html' %}

{% block title %}{{user.username}}-SmartServiceBuddy{% endblock %}
{% block content %}

<div class="container">
    <br>
    <h3></h3>



<div class="card" style="width: 18rem;">
  <img src="{{ user.servicemaninfo.profile_pic.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Hi <a href="">{{user.username}}</a>!!!!</h5>
    <p class="card-text">
Welcome to the team! We are thrilled to have you at SmartServiceBuddy. We know you’re going to be a valuable asset to our company and can’t wait to see what you accomplish.</p>
    <a href="{% url 'service_man:pending_request' %}" class="btn btn-primary">Let Do Some Action</a>
  </div>
</div>



</div>

{% endblock %}

service_man/templates/service_man/login.html
{% extends 'service_man/base.html' %}

{% block title %}Login-SmartServiceBuddy{% endblock %}
{% load bootstrap4 %}
{% block content %}



<div class="container">
 {% if user.is_authenticated%}
    <h1>already Logged In</h1>
    {% else %}
{% if form.error %}
    <h2>Your Username ans Password is incorrect...</h2>
    {% endif %}
<form method="POST" action="{% url 'service_man:login' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit"  class="btn btn-primary " name="" value="Login">


    {% endif %}

</form>
</div>



{% endblock %}

service_man/templates/service_man/past_request.html
{% extends 'service_man/base.html' %}

{% block title %}Past Request-SmartServiceBuddy{% endblock %}
{% block content %}
<div  class="centerstage">
    {% for request in clientrequest_list %}
    {% ifequal user.username|cut:" " request.service_man|cut:" " %}
    {% if request.verfication_status %}

    <div class="container" >
        <h1><a href="{% url 'service_man:request_detail' pk=request.pk %}">{{request.email}}</a></h1>
        <div class="date">
            <p>Appointment on:{{request.appointment_date|date:"d M Y"}}</p>
    </div>
    </div>
                  {% endif %}
             {% endifequal %}
         {% endfor %}


    </div>
        {% endblock %}

service_man/templates/service_man/pending_request.html
{% extends 'service_man/base.html' %}

{% block title %}Pending Request-SmartServiceBuddy{% endblock %}
{% block content %}
<div  class="centerstage">
    {% for request in clientrequest_list %}
    {% ifequal user.username|cut:" " request.service_man|cut:" " %}
        {% if request.verfication_status %}
        <div class="container" >
        <h1><a href="{% url 'service_man:request_detail' pk=request.pk %}">{{request.email}}</a></h1>
            <div class="date">
            <p>Appointment on:{{request.appointment_date|date:"d M Y"}}</p>
            </div>
            </div>
            {% endif %}
    {% endifequal %}
         {% endfor %}



    </div>
        {% endblock %}

service_man/templates/service_man/request_detail.html
{% extends 'service_man/base.html' %}

{% block title %}Request Detail-SmartServiceBuddy{% endblock %}
{% block content %}

<div class="container ">


    <p>Name :- <b><u>{{clientrequest.name}}</u></b></p>
    <p>Mobile :- <b><u>{{clientrequest.mobile}}</u></b></p>
    <p>Email :- <b><u>{{clientrequest.email}}</u></b></p>
    <p>Pincode :- <b><u>{{clientrequest.pincode}}</u></b></p>
    <p>Address:- <b><u>{{clientrequest.address}}</u></b></p>
    <p>Appliance_type:- <b><u>{{clientrequest.appliance_type}}</u></b></p>
    <p>Appliance_brand:- <b><u>{{clientrequest.appliance_brand}}</u></b></p>
    <p>Appliance_model:- <b><u>{{clientrequest.appliance_model}}</u></b></p>
    <p>Warranty:- <b><u>{{clientrequest.warranty}}</u></b></p>
    <p>Problem_description:- <b><u>{{clientrequest.problem_description}}</u></b></p>
    <p>Request_date:- <b><u>{{clientrequest.request_date}}</u></b></p>
    <p>Appointment_date:- <b><u>{{clientrequest.appointment_date}}</u></b></p>
    <p>Appointment_time:- <b><u>{{clientrequest.appointment_time}}</u></b></p>
    <p>Charge:- <b><u>{{clientrequest.charge}}</u></b></p>
    <p>Service Status:- <b><u>{{clientrequest.request_status}}</u></b></p>
<br>
    <a class="btn btn-primary" href="{% url 'service_man:request_update' pk=clientrequest.pk %}">Update Status</a>
</div>

{% endblock %}

service_man/templates/service_man/service_done_request.html
{% extends 'service_man/base.html' %}

{% block title %}Service Done Request-SmartServiceBuddy{% endblock %}
{% block content %}
<div  class="centerstage">



    {% for request in clientrequest_list %}
    {% ifequal user.username|cut:" " request.service_man|cut:" " %}
        {% if request.verfication_status %}



        <div class="container" >
        <h1><a href="{% url 'service_man:request_detail' pk=request.pk %}">{{request.email}}</a></h1>
            <div class="date">
            <p>Appointment on:{{request.appointment_date|date:"d M Y"}}</p>
            </div>
</div>


            {% endif %}
                    {% endifequal %}
         {% endfor %}



    </div>
        {% endblock %}

service_man/templates/service_man/update_request_form.html
{% extends 'service_man/base.html' %}

{% block title %}Update Request-SmartServiceBuddy{% endblock %}
{% load bootstrap4 %}
{% block content %}
  <div class="loader">
    <div class="container" ><h1><i>Service Request</i></h1></div>
    <div class="container">
    <form method="POST" >
    {% csrf_token %}
    {{form.as_p}}


    <input type="submit" class="btn btn-primary" value="Update Status">
    </form>
    </div>
  </div>
{% endblock %}